In [4]:
import pandas as pd

In [5]:
# CRUD OPERATIONS PERFORM

In [6]:
#There are two DataStructure

In [7]:
#1)Series

In [8]:
num=[1,2,3,4,5] # list is simple way to create, filter, and manipulate DataFrames and Series.
print(pd.Series(num)) # a attribute is start with capital

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
num=[1,2,3,4,5]
fun=['(a)','(b)','(c)','(d)','(e)']
print(pd.Series(num,index=fun))

(a)    1
(b)    2
(c)    3
(d)    4
(e)    5
dtype: int64

In [10]:
#2)Data Frame
#it is diffrent from 2D array format because dataframe store multiple datatypes and 2D format will store only one datatypes

In [11]:
ram=([[1,2,3,4,5],[2,4,6,7,4],[9,2,8,2,5],[3,4,5,7,2],[3,5,2,3,1]])
gun=['B','I','N','G','O']
print(pd.DataFrame(ram,index=gun,columns=gun))

   B  I  N  G  O
B  1  2  3  4  5
I  2  4  6  7  4
N  9  2  8  2  5
G  3  4  5  7  2
O  3  5  2  3  1

In [12]:
data=pd.read_csv(r"C:\Users\VISHAL SINGH\Downloads\customers-100.csv") # For read any file give read_(  ) (csv,excel,fether,Parquet)
print(data)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

In [13]:
data.head() # for first 5 rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [14]:
data.tail() # last five rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [15]:
data.head(10) #  How many- same for tail also

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [16]:
data.sample()# take a random sample from data

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
42,43,7E441b6B228DBcA,Wayne,Simpson,Perkins-Trevino,East Rebekahborough,Bolivia,(344)156-8632x1869,463-445-3702x38463,barbarapittman@holder.com,2020-12-13,https://gillespie-holder.com/

In [17]:
data.sample(5)# it will always give random dataset after every refresh

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
51,52,e898eEB1B9FE22b,Samuel,Crawford,"May, Goodwin and Martin",South Jasmine,Algeria,802-242-7457,626.116.9535x8578,xpittman@ritter-carney.net,2021-03-27,https://guerrero.org/
49,50,80F33Fd2AcebF05,Latoya,Mccann,"Hobbs, Garrett and Sanford",Port Sergiofort,Belarus,(530)287-4548x29481,162-234-0249x32790,bobhammond@barry.biz,2021-12-02,https://www.burton.com/
22,23,2FB0FAA1d429421,Colleen,Howard,Greer and Sons,Brittanyview,Paraguay,1935085151,(947)115-7711x5488,rsingleton@ryan-cherry.com,2020-08-19,http://paul.biz/
62,63,aEcbe5365BbC67D,Eddie,Jimenez,Caldwell Group,West Kristine,Ethiopia,+1-235-657-1073x6306,(026)401-7353x2417,kristiwhitney@bernard.com,2022-03-24,http://cherry.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/

In [18]:
data.sample(5,random_state=11)# here (5) means take random five data from table & (11) means those five data define name is 11

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
46,47,300A40d3ce24bBA,Geoffrey,Guzman,Short-Wiggins,Zimmermanland,Uzbekistan,975.235.8921x269,(983)188-6873,bauercrystal@gay.com,2020-04-23,https://decker-kline.com/
49,50,80F33Fd2AcebF05,Latoya,Mccann,"Hobbs, Garrett and Sanford",Port Sergiofort,Belarus,(530)287-4548x29481,162-234-0249x32790,bobhammond@barry.biz,2021-12-02,https://www.burton.com/
22,23,2FB0FAA1d429421,Colleen,Howard,Greer and Sons,Brittanyview,Paraguay,1935085151,(947)115-7711x5488,rsingleton@ryan-cherry.com,2020-08-19,http://paul.biz/
58,59,8c7DdF10798bCC3,Kathy,Hill,"Moore, Mccoy and Glass",Selenabury,South Georgia and the South Sandwich Islands,001-171-716-2175x310,888.625.0654,ncamacho@boone-simmons.org,2020-11-15,http://hayden.com/
41,42,6e5ad5a5e2bB5Ca,Bryan,Dunn,Kaufman and Sons,North Jimstad,Burkina Faso,001-710-802-5565,078.699.8982x13881,woodwardandres@phelps.com,2021-09-08,http://www.butler.com/

In [19]:
data.columns # For only all columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [20]:
list(data.columns) # columns in list form

['Index',
 'Customer Id',
 'First Name',
 'Last Name',
 'Company',
 'City',
 'Country',
 'Phone 1',
 'Phone 2',
 'Email',
 'Subscription Date',
 'Website']

In [21]:
data.index # for only index

RangeIndex(start=0, stop=100, step=1)

In [22]:
data.shape # it will show how many rows and columns are present in table (r,c)

(100, 12)

In [23]:
data.describe() # overview of table

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [24]:
data.info() #full information about table data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [25]:
## ACCESSING DATA

In [26]:
#1)loc=location 
#location based indexing

In [27]:
data.loc[1] # find particular person name by its index number

Index                                    2
Customer Id                1Ef7b82A4CAAD10
First Name                         Preston
Last Name                           Lozano
Company                        Vega-Gentry
City                     East Jimmychester
Country                           Djibouti
Phone 1                         5153435776
Phone 2                   686-620-1820x944
Email                      vmata@colon.com
Subscription Date               2021-04-23
Website              http://www.hobbs.com/
Name: 1, dtype: object

In [28]:
data.loc[1,'City'] # also for particular columns

'East Jimmychester'

In [29]:
data.loc[[0,3,5,9],'First Name'] # multiple rows you want

0      Sheryl
3       Linda
5       Aimee
9    Michelle
Name: First Name, dtype: object

In [30]:
data.loc[[1,3,6,9],['First Name','City']] # for find many columns more then one then we use list means square bracket[]

  First Name               City
1    Preston  East Jimmychester
3      Linda         Bensonview
6     Darren           Lake Ana
9   Michelle         Elaineberg

In [31]:
data.loc[0:5,'City'] # it is also used range which is exclusive in row and columns

0         East Leonard
1    East Jimmychester
2        Isabelborough
3           Bensonview
4       West Priscilla
5        Chavezborough
Name: City, dtype: object

In [32]:
data.loc[0:5,'First Name':'City'] # When we use range in columns we dont use list for that

  First Name Last Name                          Company               City
0     Sheryl    Baxter                  Rasmussen Group       East Leonard
1    Preston    Lozano                      Vega-Gentry  East Jimmychester
2        Roy     Berry                    Murillo-Perry      Isabelborough
3      Linda     Olsen  Dominguez, Mcmillan and Donovan         Bensonview
4     Joanna    Bender         Martin, Lang and Andrade     West Priscilla
5      Aimee     Downs                     Steele Group      Chavezborough

In [33]:
#iloc=integer location
#integer location based indexing

In [34]:
data.iloc[0:5,0:10]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net

In [35]:
data.iloc[[1,3,5,7],[2,5,4,9]]

,First Name,City,Company,Email
1,Preston,East Jimmychester,Vega-Gentry,vmata@colon.com
3,Linda,Bensonview,"Dominguez, Mcmillan and Donovan",stanleyblackwell@benson.org
5,Aimee,Chavezborough,Steele Group,louis27@gilbert.com
7,Brett,Kimport,"Sanford, Davenport and Giles",asnow@colon.com

In [36]:
data.at[1, 'City'] #- Access a single value by row label and column label.

'East Jimmychester'

In [37]:
data.iat[0, 10] #- Access a single value by row index (integer position) and column index (integer position).

'2020-08-24'

In [38]:
# For accessing particular columns

In [39]:
data['City']

0          East Leonard
1     East Jimmychester
2         Isabelborough
3            Bensonview
4        West Priscilla
            ...
95         East Richard
96         New Bradview
97           Ortegaland
98      Lake Elijahview
99            Judymouth
Name: City, Length: 100, dtype: object

In [40]:
data[['City','First Name']]

                 City First Name
0        East Leonard     Sheryl
1   East Jimmychester    Preston
2       Isabelborough        Roy
3          Bensonview      Linda
4      West Priscilla     Joanna
..                ...        ...
95       East Richard       Karl
96       New Bradview       Lynn
97         Ortegaland       Fred
98    Lake Elijahview     Yvonne
99          Judymouth   Clarence

[100 rows x 2 columns]

In [41]:
## NOW LETS BEGIN

In [42]:
data.head(20)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/
10,11,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,2021-10-20,https://simmons-hurley.com/
11,12,CEDec94deE6d69B,Jenna,Dodson,"Hoffman, Reed and Mcclain",East Andrea,Vietnam,(041)737-3846,+1-556-888-3485x42608,mark42@robbins.com,2020-11-29,http://www.douglas.net/
12,13,e35426EbDEceaFF,Tracey,Mata,Graham-Francis,South Joannamouth,Togo,001-949-844-8787,(855)713-8773,alex56@walls.org,2021-12-02,http://www.beck.com/
13,14,A08A8aF8BE9FaD4,Kristine,Cox,Carpenter-Cook,Jodyberg,Sri Lanka,786-284-3358x62152,+1-315-627-1796x8074,holdenmiranda@clarke.com,2021-02-08,https://www.brandt.com/
14,15,6fEaA1b7cab7B6C,Faith,Lutz,Carter-Hancock,Burchbury,Singapore,(781)861-7180x8306,207-185-3665,cassieparrish@blevins-chapman.net,2022-01-26,http://stevenson.org/
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
16,17,a5DC21AE3a21eaA,Caroline,Foley,Winters-Mendoza,West Adriennestad,Western Sahara,936.222.4746x9924,001-469-948-6341x359,holtgwendolyn@watson-davenport.com,2021-03-10,http://www.benson-roth.com/
17,18,F8Aa9d6DfcBeeF8,Greg,Mata,Valentine LLC,Lake Leslie,Mozambique,(701)087-2415,(195)156-1861x26241,jaredjuarez@carroll.org,2022-03-26,http://pitts-cherry.com/
18,19,F160f5Db3EfE973,Clifford,Jacobson,Simon LLC,Harmonview,South Georgia and the South Sandwich Islands,001-151-330-3524x0469,(748)477-7174,joseph26@jacobson.com,2020-09-24,https://mcconnell.com/
19,20,0F60FF3DdCd7aB0,Joanna,Kirk,Mays-Mccormick,Jamesshire,French Polynesia,(266)131-7001x711,(283)312-5579x11543,tuckerangie@salazar.net,2021-09-24,https://www.camacho.net/

In [43]:
data.loc[data['Country']=='Oman'] # Use (==) for find any related value

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
83,84,78C06E9b6B3DF20,Chad,Davidson,Garcia-Jimenez,South Joshuashire,Oman,8275702958,(804)842-4715,justinwalters@jimenez.com,2021-11-15,http://www.garner-oliver.com/

In [44]:
data.loc[(data['Country']=='Oman') & (data['First Name']=='Miranda')] # use () bracket when you compare with each other

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/

In [45]:
data.loc[(data['Country']=='Oman') | (data['First Name']=='Miranda')]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
83,84,78C06E9b6B3DF20,Chad,Davidson,Garcia-Jimenez,South Joshuashire,Oman,8275702958,(804)842-4715,justinwalters@jimenez.com,2021-11-15,http://www.garner-oliver.com/

In [46]:
# Above all things will also do by without using (loc) method like below it will says(short hand method)

In [47]:
# in this we only use for columns not rows

In [48]:
data[(data['Country']=='Oman') | (data['First Name']=='Miranda')]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
15,16,8cad0b4CBceaeec,Miranda,Beasley,Singleton and Sons,Desireeshire,Oman,540.085.3135x185,+1-600-462-6432x21881,vduncan@parks-hardy.com,2022-04-12,http://acosta.org/
83,84,78C06E9b6B3DF20,Chad,Davidson,Garcia-Jimenez,South Joshuashire,Oman,8275702958,(804)842-4715,justinwalters@jimenez.com,2021-11-15,http://www.garner-oliver.com/

In [49]:
data.loc[data['Country'].str.contains('Sr')] # here with .str. we use many other functions with string like str.split

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
13,14,A08A8aF8BE9FaD4,Kristine,Cox,Carpenter-Cook,Jodyberg,Sri Lanka,786-284-3358x62152,+1-315-627-1796x8074,holdenmiranda@clarke.com,2021-02-08,https://www.brandt.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/

In [50]:
# update in table

In [51]:
data.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [52]:
data.loc[2,'First Name']='Vishal'
data.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Vishal,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [53]:
data.loc[0:6,'Country']='India'
data.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,India,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,India,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Vishal,Berry,Murillo-Perry,Isabelborough,India,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,India,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,India,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,India,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,India,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [54]:
data.loc[[2,4,8],'Country']='New Zeland'
data.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,India,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,India,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Vishal,Berry,Murillo-Perry,Isabelborough,New Zeland,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,India,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,New Zeland,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,India,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,India,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,New Zeland,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [55]:
# same as iloc but it is integer based position loc

In [56]:
data.iloc[2,3]='singh'
data.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,India,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,India,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Vishal,singh,Murillo-Perry,Isabelborough,New Zeland,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,India,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,New Zeland,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [57]:
data.at[0:1,'Last Name']='Dubey'
data.head(8)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Dubey,Rasmussen Group,East Leonard,India,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Dubey,Vega-Gentry,East Jimmychester,India,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Vishal,singh,Murillo-Perry,Isabelborough,New Zeland,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,India,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,New Zeland,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,India,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,India,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/

In [58]:
data.iat[1,5]='surat'
data.head(8)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Dubey,Rasmussen Group,East Leonard,India,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Dubey,Vega-Gentry,surat,India,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Vishal,singh,Murillo-Perry,Isabelborough,New Zeland,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,India,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,New Zeland,001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,India,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,India,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/

In [59]:
data=pd.read_csv(r"C:\Users\VISHAL SINGH\Downloads\customers-100.csv") # if you have to find previous value then you have to open further csv file
print(data)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

In [60]:
data.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [61]:
data.loc[0:1,'City']='Bangumra'
data.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Bangumra,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,Bangumra,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [62]:
# we also use short hand method

In [63]:
data['City']='Surat'
data.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,Surat,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,Surat,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Surat,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [64]:
# When we have to do manipulation in columns we used to  apply()
# for example only

In [65]:
def arrange_characters(x):
    return ''.join(sorted(x))

what=data['First Name'].apply(arrange_characters) # it will not impact original data set
what.head(10)

0      Sehlry
1     Penorst
2         Roy
3       Ladin
4      Jaanno
5       Aeeim
6      Daenrr
7       Bertt
8      Sehlry
9    Mceehill
Name: First Name, dtype: object

In [66]:
# use lambda for reverse process example
# observe=data['roll no'].apply(lambda x:x-5)
# print(observe)

In [67]:
#NOTE: And when if we have to create new columns then use 
# observe['Age Category']=data['Age'].apply(lambda x:'very Young' if x>20 else 'underage' )
# observe['Age Category'].head(5)

In [68]:
## NOTE:  If we add any columns at particular position then use (INSERT)

In [69]:
data.insert(4,'Age',18)

In [70]:
data.head(10)

,Index,Customer Id,First Name,Last Name,Age,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,18,Steele Group,Surat,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,18,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,18,"Sanford, Davenport and Giles",Surat,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,18,Browning-Simon,Surat,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,18,Beck-Hendrix,Surat,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [71]:
# If we have to delete particular columns then use (DROP)

In [72]:
data.drop(columns='Phone 2') # But it will not impact original data frame

,Index,Customer Id,First Name,Last Name,Age,Company,City,Country,Phone 1,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,229.077.5154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,18,Carey LLC,Surat,Guyana,(188)169-1674x58692,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,18,"Ware, Burns and Oneal",Surat,Sri Lanka,+1-846-706-2218,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,18,Schmitt-Jones,Surat,Solomon Islands,+1-753-067-8419x7170,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,18,Fitzgerald-Harrell,Surat,Aruba,(530)311-9786,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,18,"Le, Nash and Cross",Surat,Honduras,(753)813-6941,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [73]:
# for imapct original data frame use(inplace=True)

In [74]:
data.drop(columns='Phone 2',inplace=True )

In [75]:
data.head(10)

,Index,Customer Id,First Name,Last Name,Age,Company,City,Country,Phone 1,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,229.077.5154,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,5153435776,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,+1-539-402-0259,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,001-808-617-6467x12895,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),001-234-203-0635x76146,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,18,Steele Group,Surat,Bosnia and Herzegovina,(283)437-3886x88321,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,18,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,(496)452-6181x3291,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,18,"Sanford, Davenport and Giles",Surat,Bulgaria,001-583-352-7197x297,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,18,Browning-Simon,Surat,Cyprus,854-138-4911x5772,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,18,Beck-Hendrix,Surat,Timor-Leste,739.218.2516x459,mdyer@escobar.net,2021-11-08,https://arias.com/

In [76]:
# # if we have to drop more then one column then use # NOTE: USE SQUARE BRACKET
data.drop(columns=['Phone 1','Website'],inplace=True)

In [77]:
data.head(10)

,Index,Customer Id,First Name,Last Name,Age,Company,City,Country,Email,Subscription Date
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,zunigavanessa@smith.info,2020-08-24
1,2,1Ef7b82A4CAAD10,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,6F94879bDAfE5a6,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,5Cef8BFA16c5e3c,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,stanleyblackwell@benson.org,2020-06-02
4,5,053d585Ab6b3159,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),colinalvarado@miles.net,2021-04-17
5,6,2d08FB17EE273F4,Aimee,Downs,18,Steele Group,Surat,Bosnia and Herzegovina,louis27@gilbert.com,2020-02-25
6,7,EA4d384DfDbBf77,Darren,Peck,18,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,0e04AFde9f225dE,Brett,Mullen,18,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,18,Browning-Simon,Surat,Cyprus,mariokhan@ryan-pope.org,2020-01-13
9,10,8C2811a503C7c5a,Michelle,Gallagher,18,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [78]:
# NOTE
del data['Customer Id'] # it is important because it is shortcut methode & #NOTE: It will direct impact in original dataframe 
data.head(5)

,Index,First Name,Last Name,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,stanleyblackwell@benson.org,2020-06-02
4,5,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),colinalvarado@miles.net,2021-04-17

In [79]:
# NOTE
data.rename(columns={'Last Name':'Surname'}) # temporary chnage # use {} curly bracket for rename

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,stanleyblackwell@benson.org,2020-06-02
4,5,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),colinalvarado@miles.net,2021-04-17
...,...,...,...,...,...,...,...,...,...
95,96,Karl,Greer,18,Carey LLC,Surat,Guyana,hhart@jensen.com,2022-01-30
96,97,Lynn,Atkinson,18,"Ware, Burns and Oneal",Surat,Sri Lanka,vkemp@ferrell.com,2021-07-10
97,98,Fred,Guerra,18,Schmitt-Jones,Surat,Solomon Islands,swagner@kane.org,2021-09-18
98,99,Yvonne,Farmer,18,Fitzgerald-Harrell,Surat,Aruba,mccarthystephen@horn-green.biz,2021-08-11
99,100,Clarence,Haynes,18,"Le, Nash and Cross",Surat,Honduras,colleen91@faulkner.biz,2020-03-11

In [80]:
data.rename(columns={'Last Name':'Surname'},inplace=True) # parmanent change

In [81]:
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,stanleyblackwell@benson.org,2020-06-02
4,5,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),colinalvarado@miles.net,2021-04-17
5,6,Aimee,Downs,18,Steele Group,Surat,Bosnia and Herzegovina,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18,Browning-Simon,Surat,Cyprus,mariokhan@ryan-pope.org,2020-01-13
9,10,Michelle,Gallagher,18,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [82]:
# NOTE: MERGE TWO DATAFRAME

df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Aman','Ram','Rahul','Geeta']
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'course':['GenAI','Python','WEB-Dev','ML']
})

yes=pd.merge(df1,df2,'inner','id') #(left,right,how,on)
yes.head()

   id   name  course
0   3  Rahul   GenAI
1   4  Geeta  Python

In [83]:
yes=pd.merge(df1,df2,'left','id') #(left,right,how,on)
yes.head()

   id   name  course
0   1   Aman     NaN
1   2    Ram     NaN
2   3  Rahul   GenAI
3   4  Geeta  Python

In [84]:
yes=pd.merge(df1,df2,'right','id') #(left,right,how,on)
yes.head()

   id   name   course
0   3  Rahul    GenAI
1   4  Geeta   Python
2   5    NaN  WEB-Dev
3   6    NaN       ML

In [85]:
yes=pd.merge(df1,df2,'outer','id') #(left,right,how,on)
yes.head()

   id   name   course
0   1   Aman      NaN
1   2    Ram      NaN
2   3  Rahul    GenAI
3   4  Geeta   Python
4   5    NaN  WEB-Dev

In [86]:
# NOTE: if we have given two labels which are contain same value but diffrent label name so how we perform such as
df3=pd.DataFrame({
    'id1':[1,2,3,4],
    'name':['Aman','Ram','Rahul','Geeta']
})

df4=pd.DataFrame({
    'id2':[3,4,5,6],
    'course':['GenAI','Python','WEB-Dev','ML']
})

yes=pd.merge(df3,df4,'inner',left_on='id1',right_on='id2')
yes.head()

   id1   name  id2  course
0    3  Rahul    3   GenAI
1    4  Geeta    4  Python

In [87]:
# for changing position 
woo = yes[['id1','id2','name','course']]
woo.head()

   id1  id2   name  course
0    3    3  Rahul   GenAI
1    4    4  Geeta  Python

In [88]:
# sometimes we have to join the dataframe or series not on the basis of some id or primary key sometimes we have to concatenate basis of row or columns

In [89]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Aman','Ram','Rahul','Geeta']
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'course':['GenAI','Python','WEB-Dev','ML']
})

waah=pd.concat([df1,df2],axis=0,ignore_index=True) # on the basis of row beacuse axis=0
waah                # only print variable not head

   id   name   course
0   1   Aman      NaN
1   2    Ram      NaN
2   3  Rahul      NaN
3   4  Geeta      NaN
4   3    NaN    GenAI
5   4    NaN   Python
6   5    NaN  WEB-Dev
7   6    NaN       ML

In [90]:
waah2=pd.concat([df1,df2],axis=1) # on the basis of columns beacuse axis=1
waah2

   id   name  id   course
0   1   Aman   3    GenAI
1   2    Ram   4   Python
2   3  Rahul   5  WEB-Dev
3   4  Geeta   6       ML

In [91]:
# for diffrenciate the two or more rows 

fun=pd.concat([df1,df2],axis=0,keys=['df1','df2'])
fun

       id   name   course
df1 0   1   Aman      NaN
    1   2    Ram      NaN
    2   3  Rahul      NaN
    3   4  Geeta      NaN
df2 0   3    NaN    GenAI
    1   4    NaN   Python
    2   5    NaN  WEB-Dev
    3   6    NaN       ML

In [92]:
## NOTE: HANDELLING NULL VALUES

In [93]:
fun.isna()

          id   name  course
df1 0  False  False    True
    1  False  False    True
    2  False  False    True
    3  False  False    True
df2 0  False   True   False
    1  False   True   False
    2  False   True   False
    3  False   True   False

In [94]:
fun.isna().sum() # how many null values

id        0
name      4
course    4
dtype: int64

In [95]:
data.isna().sum()

Index                0
First Name           0
Surname              0
Age                  0
Company              0
City                 0
Country              0
Email                0
Subscription Date    0
dtype: int64

In [96]:
fun.notna().sum() # how many without null values

id        8
name      4
course    4
dtype: int64

In [97]:
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,18,Rasmussen Group,Surat,Chile,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,18,"Dominguez, Mcmillan and Donovan",Surat,Dominican Republic,stanleyblackwell@benson.org,2020-06-02
4,5,Joanna,Bender,18,"Martin, Lang and Andrade",Surat,Slovakia (Slovak Republic),colinalvarado@miles.net,2021-04-17
5,6,Aimee,Downs,18,Steele Group,Surat,Bosnia and Herzegovina,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18,Browning-Simon,Surat,Cyprus,mariokhan@ryan-pope.org,2020-01-13
9,10,Michelle,Gallagher,18,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [98]:
import numpy as np

In [99]:
# add null values in table 
data.loc[[0,3,5],['Age','Country']]= np.nan
data.loc[[3,4,8],['Company','Email']]= np.nan
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,NaN,Rasmussen Group,Surat,NaN,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,NaN,NaN,Surat,NaN,NaN,2020-06-02
4,5,Joanna,Bender,18.0,NaN,Surat,Slovakia (Slovak Republic),NaN,2021-04-17
5,6,Aimee,Downs,NaN,Steele Group,Surat,NaN,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,NaN,Surat,Cyprus,NaN,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [100]:
data.isna().sum()

Index                0
First Name           0
Surname              0
Age                  3
Company              3
City                 0
Country              3
Email                3
Subscription Date    0
dtype: int64

In [101]:
# now fill the null value 
data.fillna(0,inplace=True)

In [102]:
# NOTE: SEE AT VARIABLE
#  fillna for  particular columns 
data['Age']=data['Age'].fillna(20)
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,0.0,Rasmussen Group,Surat,0,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,2020-03-25
3,4,Linda,Olsen,0.0,0,Surat,0,0,2020-06-02
4,5,Joanna,Bender,18.0,0,Surat,Slovakia (Slovak Republic),0,2021-04-17
5,6,Aimee,Downs,0.0,Steele Group,Surat,0,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,0,Surat,Cyprus,0,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [103]:
data.loc[[0,3,5],['Age','Country']]= np.nan
data.loc[[3,4,8],['Company','Email']]= np.nan
data.loc[2,'Subscription Date']= np.nan
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,NaN,Rasmussen Group,Surat,NaN,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,NaN
3,4,Linda,Olsen,NaN,NaN,Surat,NaN,NaN,2020-06-02
4,5,Joanna,Bender,18.0,NaN,Surat,Slovakia (Slovak Republic),NaN,2021-04-17
5,6,Aimee,Downs,NaN,Steele Group,Surat,NaN,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,NaN,Surat,Cyprus,NaN,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [104]:
# NOTE: MEAN VALUE ASIGN
data['Age']=data['Age'].fillna(data['Age'].mean())
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,18.0,Rasmussen Group,Surat,NaN,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,NaN
3,4,Linda,Olsen,18.0,NaN,Surat,NaN,NaN,2020-06-02
4,5,Joanna,Bender,18.0,NaN,Surat,Slovakia (Slovak Republic),NaN,2021-04-17
5,6,Aimee,Downs,18.0,Steele Group,Surat,NaN,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,NaN,Surat,Cyprus,NaN,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [105]:
data.loc[[0,3,5],['Age','Country']]= np.nan
data.loc[[3,4,8],['Company','Email']]= np.nan
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,NaN,Rasmussen Group,Surat,NaN,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,NaN
3,4,Linda,Olsen,NaN,NaN,Surat,NaN,NaN,2020-06-02
4,5,Joanna,Bender,18.0,NaN,Surat,Slovakia (Slovak Republic),NaN,2021-04-17
5,6,Aimee,Downs,NaN,Steele Group,Surat,NaN,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,NaN,Surat,Cyprus,NaN,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [106]:
# fill na for more then one columns (labels)
data.fillna({'Country':'India','Company':'Accenture'},inplace=True)
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,NaN,Rasmussen Group,Surat,India,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,NaN
3,4,Linda,Olsen,NaN,Accenture,Surat,India,NaN,2020-06-02
4,5,Joanna,Bender,18.0,Accenture,Surat,Slovakia (Slovak Republic),NaN,2021-04-17
5,6,Aimee,Downs,NaN,Steele Group,Surat,India,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,Accenture,Surat,Cyprus,NaN,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [107]:
data['Age']=data['Age'].fillna(data['Age'].interpolate())# ass pass ke value ka avg
data.head(10)

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
0,1,Sheryl,Baxter,NaN,Rasmussen Group,Surat,India,zunigavanessa@smith.info,2020-08-24
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
2,3,Roy,Berry,18.0,Murillo-Perry,Surat,Antigua and Barbuda,beckycarr@hogan.com,NaN
3,4,Linda,Olsen,18.0,Accenture,Surat,India,NaN,2020-06-02
4,5,Joanna,Bender,18.0,Accenture,Surat,Slovakia (Slovak Republic),NaN,2021-04-17
5,6,Aimee,Downs,18.0,Steele Group,Surat,India,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
8,9,Sheryl,Meyers,18.0,Accenture,Surat,Cyprus,NaN,2020-01-13
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08

In [108]:
data.dropna() # for remove all null values # inplace = True is also used here for original data frame

,Index,First Name,Surname,Age,Company,City,Country,Email,Subscription Date
1,2,Preston,Lozano,18.0,Vega-Gentry,Surat,Djibouti,vmata@colon.com,2021-04-23
5,6,Aimee,Downs,18.0,Steele Group,Surat,India,louis27@gilbert.com,2020-02-25
6,7,Darren,Peck,18.0,"Lester, Woodard and Mitchell",Surat,Pitcairn Islands,tgates@cantrell.com,2021-08-24
7,8,Brett,Mullen,18.0,"Sanford, Davenport and Giles",Surat,Bulgaria,asnow@colon.com,2021-04-12
9,10,Michelle,Gallagher,18.0,Beck-Hendrix,Surat,Timor-Leste,mdyer@escobar.net,2021-11-08
...,...,...,...,...,...,...,...,...,...
95,96,Karl,Greer,18.0,Carey LLC,Surat,Guyana,hhart@jensen.com,2022-01-30
96,97,Lynn,Atkinson,18.0,"Ware, Burns and Oneal",Surat,Sri Lanka,vkemp@ferrell.com,2021-07-10
97,98,Fred,Guerra,18.0,Schmitt-Jones,Surat,Solomon Islands,swagner@kane.org,2021-09-18
98,99,Yvonne,Farmer,18.0,Fitzgerald-Harrell,Surat,Aruba,mccarthystephen@horn-green.biz,2021-08-11
99,100,Clarence,Haynes,18.0,"Le, Nash and Cross",Surat,Honduras,colleen91@faulkner.biz,2020-03-11

In [109]:
# Group by

In [110]:
hello=data.groupby('Country').count()
hello.head(10)

,Index,First Name,Surname,Age,Company,City,Email,Subscription Date
Country,,,,,,,,
Albania,1,1,1,1,1,1,1,1
Algeria,1,1,1,1,1,1,1,1
Anguilla,1,1,1,1,1,1,1,1
Antigua and Barbuda,1,1,1,1,1,1,1,0
Aruba,1,1,1,1,1,1,1,1
Bahamas,1,1,1,1,1,1,1,1
Belarus,2,2,2,2,2,2,2,2
Belize,1,1,1,1,1,1,1,1
Benin,1,1,1,1,1,1,1,1
Bhutan,1,1,1,1,1,1,1,1

In [111]:
data.groupby('Country')['Age'].mean() # for finding mean

Country
Albania                18.0
Algeria                18.0
Anguilla               18.0
Antigua and Barbuda    18.0
Aruba                  18.0
                       ...
Uzbekistan             18.0
Vietnam                18.0
Western Sahara         18.0
Yemen                  18.0
Zimbabwe               18.0
Name: Age, Length: 84, dtype: float64

In [112]:
data.groupby('Country')['Age'].median()

Country
Albania                18.0
Algeria                18.0
Anguilla               18.0
Antigua and Barbuda    18.0
Aruba                  18.0
                       ...
Uzbekistan             18.0
Vietnam                18.0
Western Sahara         18.0
Yemen                  18.0
Zimbabwe               18.0
Name: Age, Length: 84, dtype: float64

In [113]:
data.groupby('Country')['Age'].agg(['sum','median']) # multiple aggregate function

                      sum  median
Country
Albania              18.0    18.0
Algeria              18.0    18.0
Anguilla             18.0    18.0
Antigua and Barbuda  18.0    18.0
Aruba                18.0    18.0
...                   ...     ...
Uzbekistan           18.0    18.0
Vietnam              18.0    18.0
Western Sahara       18.0    18.0
Yemen                18.0    18.0
Zimbabwe             36.0    18.0

[84 rows x 2 columns]